version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: spring_postgres
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivanpass
      POSTGRES_DB: ordertracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
